package com.asu.edu.daos;

// Generated Oct 21, 2014 9:01:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
@SuppressWarnings("serial")
public class Account implements java.io.Serializable {

	private String accountNumber;
	private User user;
	private boolean isBlocked;
	private String comments;
	private Date creationTime;
	private String accountType;
	private double balance;
	private Set<Transactions> transactionsesForAccountSource = new HashSet<Transactions>(
			0);
	private Set<Transactions> transactionsesForAccountTarget = new HashSet<Transactions>(
			0);

	public Account() {
	}

	public Account(String accountNumber, User user, boolean isBlocked,
			Date creationTime, String accountType, double balance) {
		this.accountNumber = accountNumber;
		this.user = user;
		this.isBlocked = isBlocked;
		this.creationTime = creationTime;
		this.accountType = accountType;
		this.balance = balance;
	}

	public Account(String accountNumber, User user, boolean isBlocked,
			String comments, Date creationTime, String accountType,
			double balance, Set<Transactions> transactionsesForAccountSource,
			Set<Transactions> transactionsesForAccountTarget) {
		this.accountNumber = accountNumber;
		this.user = user;
		this.isBlocked = isBlocked;
		this.comments = comments;
		this.creationTime = creationTime;
		this.accountType = accountType;
		this.balance = balance;
		this.transactionsesForAccountSource = transactionsesForAccountSource;
		this.transactionsesForAccountTarget = transactionsesForAccountTarget;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isIsBlocked() {
		return this.isBlocked;
	}

	public void setIsBlocked(boolean isBlocked) {
		this.isBlocked = isBlocked;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Set<Transactions> getTransactionsesForAccountSource() {
		return this.transactionsesForAccountSource;
	}

	public void setTransactionsesForAccountSource(
			Set<Transactions> transactionsesForAccountSource) {
		this.transactionsesForAccountSource = transactionsesForAccountSource;
	}

	public Set<Transactions> getTransactionsesForAccountTarget() {
		return this.transactionsesForAccountTarget;
	}

	public void setTransactionsesForAccountTarget(
			Set<Transactions> transactionsesForAccountTarget) {
		this.transactionsesForAccountTarget = transactionsesForAccountTarget;
	}
	

}
