package com.asu.edu.daos;

// Generated Nov 7, 2014 4:37:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Mappings generated by hbm2java
 */
public class Mappings implements java.io.Serializable {

	private Integer id;
	private User userByInternalUsername;
	private User userByExternalUsername;
	private String accessType;
	private boolean status;

	public Mappings() {
	}

	public Mappings(User userByInternalUsername, User userByExternalUsername,
			String accessType, boolean status) {
		this.userByInternalUsername = userByInternalUsername;
		this.userByExternalUsername = userByExternalUsername;
		this.accessType = accessType;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUserByInternalUsername() {
		return this.userByInternalUsername;
	}

	public void setUserByInternalUsername(User userByInternalUsername) {
		this.userByInternalUsername = userByInternalUsername;
	}

	public User getUserByExternalUsername() {
		return this.userByExternalUsername;
	}

	public void setUserByExternalUsername(User userByExternalUsername) {
		this.userByExternalUsername = userByExternalUsername;
	}

	public String getAccessType() {
		return this.accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
