package com.asu.edu.daos;

// Generated Nov 7, 2014 3:07:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Otp generated by hbm2java
 */
public class Otp implements java.io.Serializable {

	private OtpId id;
	private User user;

	public Otp() {
	}

	public Otp(OtpId id, User user) {
		this.id = id;
		this.user = user;
	}

	public OtpId getId() {
		return this.id;
	}

	public void setId(OtpId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
