package com.asu.edu.daos;

// Generated Oct 21, 2014 9:01:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private RolesId id;

	public Roles() {
	}

	public Roles(RolesId id) {
		this.id = id;
	}

	public RolesId getId() {
		return this.id;
	}

	public void setId(RolesId id) {
		this.id = id;
	}

}
