package com.asu.edu.daos;

// Generated Oct 31, 2014 3:28:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private String transactionId;
	private Account accountByAccountTarget;
	private Account accountByAccountSource;
	private double transactionAmount;
	private String transactionType;
	private String transactionStatus;
	private boolean isCritical;
	private Date transactionTime;

	public Transactions() {
	}

	public Transactions(String transactionId, Account accountByAccountTarget,
			Account accountByAccountSource, double transactionAmount,
			String transactionType, String transactionStatus,
			boolean isCritical, Date transactionTime) {
		this.transactionId = transactionId;
		this.accountByAccountTarget = accountByAccountTarget;
		this.accountByAccountSource = accountByAccountSource;
		this.transactionAmount = transactionAmount;
		this.transactionType = transactionType;
		this.transactionStatus = transactionStatus;
		this.isCritical = isCritical;
		this.transactionTime = transactionTime;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public Account getAccountByAccountTarget() {
		return this.accountByAccountTarget;
	}

	public void setAccountByAccountTarget(Account accountByAccountTarget) {
		this.accountByAccountTarget = accountByAccountTarget;
	}

	public Account getAccountByAccountSource() {
		return this.accountByAccountSource;
	}

	public void setAccountByAccountSource(Account accountByAccountSource) {
		this.accountByAccountSource = accountByAccountSource;
	}

	public double getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(double transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public String getTransactionStatus() {
		return this.transactionStatus;
	}

	public void setTransactionStatus(String transactionStatus) {
		this.transactionStatus = transactionStatus;
	}

	public boolean isIsCritical() {
		return this.isCritical;
	}

	public void setIsCritical(boolean isCritical) {
		this.isCritical = isCritical;
	}

	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

}
