package com.asu.edu.daos;

// Generated Oct 21, 2014 9:01:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.hibernate.cfg.Mappings;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	private String username;
	private String email;
	private String address;
	private String password;
	private String phoneNumber;
	private boolean enabled;
	private String name;
	private int pii;
	private String publicKey;
	private Set<Mappings> mappingsesForInternalUsername = new HashSet<Mappings>(
			0);
	private Set<Mappings> mappingsesForExternalUsername = new HashSet<Mappings>(
			0);
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Otp> otps = new HashSet<Otp>(0);

	public User() {
	}

	public User(String username, String email, String password,
			String phoneNumber, boolean enabled, String name, int pii,
			String publicKey) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.phoneNumber = phoneNumber;
		this.enabled = enabled;
		this.name = name;
		this.pii = pii;
		this.publicKey = publicKey;
	}

	public User(String username, String email, String address, String password,
			String phoneNumber, boolean enabled, String name, int pii,
			String publicKey, Set<Mappings> mappingsesForInternalUsername,
			Set<Mappings> mappingsesForExternalUsername, Set<Account> accounts,
			Set<Otp> otps) {
		this.username = username;
		this.email = email;
		this.address = address;
		this.password = password;
		this.phoneNumber = phoneNumber;
		this.enabled = enabled;
		this.name = name;
		this.pii = pii;
		this.publicKey = publicKey;
		this.mappingsesForInternalUsername = mappingsesForInternalUsername;
		this.mappingsesForExternalUsername = mappingsesForExternalUsername;
		this.accounts = accounts;
		this.otps = otps;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPii() {
		return this.pii;
	}

	public void setPii(int pii) {
		this.pii = pii;
	}

	public String getPublicKey() {
		return this.publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	public Set<Mappings> getMappingsesForInternalUsername() {
		return this.mappingsesForInternalUsername;
	}

	public void setMappingsesForInternalUsername(
			Set<Mappings> mappingsesForInternalUsername) {
		this.mappingsesForInternalUsername = mappingsesForInternalUsername;
	}

	public Set<Mappings> getMappingsesForExternalUsername() {
		return this.mappingsesForExternalUsername;
	}

	public void setMappingsesForExternalUsername(
			Set<Mappings> mappingsesForExternalUsername) {
		this.mappingsesForExternalUsername = mappingsesForExternalUsername;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	public Set<Otp> getOtps() {
		return this.otps;
	}

	public void setOtps(Set<Otp> otps) {
		this.otps = otps;
	}

}
